name: sass_builder_example
version: 0.0.1
description: Example that outputs the .css to the source directory.
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  bootstrap_sass: 4.0.0-alpha.5+1
dev_dependencies:
  build_runner: ^0.7.5+1
  sass_builder:
    path: ../
